name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build-and-deploy
        run: |
          git fetch origin 
          git reset --hard origin/main 
          git clean -f -d
          docker compose -f docker-compose.prod.yml up --build --detach