name: run tests on call

on:
  push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Goto client and run tests
        run: cd web-app && npm i && npm test