name: run tests on call

on:
  push

jobs:
  test-web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: build front end and run tests
        run: docker compose -f docker-compose.ci-front.yml up --build --exit-code-from web-app
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: run back end tests
        run: docker compose -f docker-compose.ci-back.yml up --build --exit-code-from web-app

