name: run tests on call

on:
  push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build app
        run: docker compose up --build
      - name: run front end tests
        run: docker compose exec web-app npm test
      - name: run back end tests
        run: docker compose exec back-app npm test